### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by GMCfromhell** [ExpressoBits/expressobits.github.io#1]
Navbar expanding (Dropdown Menu) without background on lower resolutions.

**Comment by scriptsengineer** [comment]
Consult enrico about this?

**Comment by GMCfromhell** [comment]
Removed Affix Scripts and Bootstrap, Fixed mobile responsive Navbar.
Fully functional on lower resolutions now.
Thanks everyone who helped.
